// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ModernWMS.Core.DBContext;

#nullable disable

namespace ModernWMS.Migrations.SqlServer.Migrations
{
    [DbContext(typeof(SqlDBContext))]
    partial class SqlDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ModernWMS.Core.Models.GlobalUniqueSerialEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("current_no")
                        .HasColumnType("int");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("prefix_char")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reset_rule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("table_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("global_unique_serial");
                });

            modelBuilder.Entity("ModernWMS.Core.Models.UserEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("AuthString")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("auth_string");

                    b.Property<string>("ContactTel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("contact_tel");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("create_time");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("creator");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit")
                        .HasColumnName("is_valid");

                    b.Property<DateTime>("LastUpdateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_update_time");

                    b.Property<string>("Sex")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sex");

                    b.Property<long>("TenantId")
                        .HasColumnType("bigint")
                        .HasColumnName("tenant_id");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_name");

                    b.Property<string>("UserNum")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_num");

                    b.Property<string>("UserRole")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_role");

                    b.HasKey("id");

                    b.ToTable("user");
                });

            modelBuilder.Entity("ModernWMS.Core.Models.UserroleEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_valid")
                        .HasColumnType("bit");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("role_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("userrole");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.ActionLogEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("action_content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("action_time")
                        .HasColumnType("datetime2");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.Property<string>("user_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vue_path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("action_log");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.Approve.FlowSetMainEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("flow_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("menu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("flowsetmain");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.AsnEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("actual_qty")
                        .HasColumnType("int");

                    b.Property<DateTime>("arrival_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("asn_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("asn_qty")
                        .HasColumnType("int");

                    b.Property<byte>("asn_status")
                        .HasColumnType("tinyint");

                    b.Property<int>("asnmaster_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("damage_qty")
                        .HasColumnType("int");

                    b.Property<DateTime>("expiry_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("goods_owner_id")
                        .HasColumnType("int");

                    b.Property<string>("goods_owner_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_valid")
                        .HasColumnType("bit");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime2");

                    b.Property<int>("more_qty")
                        .HasColumnType("int");

                    b.Property<decimal>("price")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("shortage_qty")
                        .HasColumnType("int");

                    b.Property<int>("sku_id")
                        .HasColumnType("int");

                    b.Property<int>("sorted_qty")
                        .HasColumnType("int");

                    b.Property<int>("spu_id")
                        .HasColumnType("int");

                    b.Property<int>("supplier_id")
                        .HasColumnType("int");

                    b.Property<string>("supplier_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.Property<string>("unload_person")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("unload_person_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("unload_time")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("volume")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("weight")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("id");

                    b.HasIndex("asnmaster_id");

                    b.ToTable("asn");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.AsnMasterEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("asn_batch")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("asn_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("asn_status")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("estimated_arrival_time")
                        .HasColumnType("datetime2");

                    b.Property<int>("goods_owner_id")
                        .HasColumnType("int");

                    b.Property<string>("goods_owner_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime2");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("volume")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("weight")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("id");

                    b.ToTable("asnmaster");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.AsnSortEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("asn_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_valid")
                        .HasColumnType("bit");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime2");

                    b.Property<int>("putaway_qty")
                        .HasColumnType("int");

                    b.Property<string>("series_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sorted_qty")
                        .HasColumnType("int");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("asnsort");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.CategoryEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("category_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_valid")
                        .HasColumnType("bit");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime2");

                    b.Property<int>("parent_id")
                        .HasColumnType("int");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("category");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.CompanyEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("company_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contact_tel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("manager")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("company");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.CustomerEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contact_tel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("customer_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_valid")
                        .HasColumnType("bit");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("manager")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("customer");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.DispatchListEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("actual_qty")
                        .HasColumnType("int");

                    b.Property<string>("carrier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("customer_id")
                        .HasColumnType("int");

                    b.Property<string>("customer_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("damage_qty")
                        .HasColumnType("int");

                    b.Property<string>("dispatch_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("dispatch_status")
                        .HasColumnType("tinyint");

                    b.Property<decimal>("freightfee")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<int>("intrasit_qty")
                        .HasColumnType("int");

                    b.Property<DateTime>("last_update_time")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<int>("lock_qty")
                        .HasColumnType("int");

                    b.Property<string>("package_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("package_person")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("package_qty")
                        .HasColumnType("int");

                    b.Property<DateTime>("package_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("pick_checker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("pick_checker_id")
                        .HasColumnType("int");

                    b.Property<int>("picked_qty")
                        .HasColumnType("int");

                    b.Property<int>("qty")
                        .HasColumnType("int");

                    b.Property<int>("sign_qty")
                        .HasColumnType("int");

                    b.Property<int>("sku_id")
                        .HasColumnType("int");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.Property<decimal>("volume")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("waybill_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("weighing_no")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("weighing_person")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("weighing_qty")
                        .HasColumnType("int");

                    b.Property<decimal>("weighing_weight")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("weight")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("id");

                    b.ToTable("dispatchlist");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.DispatchPickListEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("dispatchlist_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("expiry_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("goods_location_id")
                        .HasColumnType("int");

                    b.Property<int>("goods_owner_id")
                        .HasColumnType("int");

                    b.Property<bool>("is_update_stock")
                        .HasColumnType("bit");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime2");

                    b.Property<int>("pick_qty")
                        .HasColumnType("int");

                    b.Property<int>("picked_qty")
                        .HasColumnType("int");

                    b.Property<string>("picker")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("picker_id")
                        .HasColumnType("int");

                    b.Property<decimal>("price")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("putaway_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("series_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sku_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("dispatchlist_id");

                    b.ToTable("dispatchpicklist");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.FlowSetEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("flowsetmain_id")
                        .HasColumnType("int");

                    b.Property<bool>("is_end")
                        .HasColumnType("bit");

                    b.Property<bool>("is_origin")
                        .HasColumnType("bit");

                    b.Property<string>("node_guid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("node_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("prev_node_guid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("flowsetmain_id");

                    b.ToTable("flowset");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.FlowSetFilterEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("assert_mode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("c2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("col_label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("col_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("compare")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("condition_group")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("flowset_id")
                        .HasColumnType("int");

                    b.Property<int>("flowsetmain_id")
                        .HasColumnType("int");

                    b.Property<string>("formulas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("logic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("node_guid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("scheme_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sort")
                        .HasColumnType("int");

                    b.Property<string>("table_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("flowset_id");

                    b.ToTable("flowsetfilter");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.FlowSetUserEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("flowset_id")
                        .HasColumnType("int");

                    b.Property<int>("flowsetmain_id")
                        .HasColumnType("int");

                    b.Property<string>("node_guid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("user_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("flowset_id");

                    b.ToTable("flowsetusers");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.FreightFeeEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("arrival_city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("carrier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("departure_city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_valid")
                        .HasColumnType("bit");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("min_payment")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("price_per_volume")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("price_per_weight")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("freightfee");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.GoodsLocationEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_valid")
                        .HasColumnType("bit");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("layer_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("location_heigth")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("location_length")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("location_load")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("location_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("location_volume")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("location_width")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("roadway_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("shelf_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tag_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.Property<int>("warehouse_area_id")
                        .HasColumnType("int");

                    b.Property<string>("warehouse_area_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("warehouse_area_property")
                        .HasColumnType("tinyint");

                    b.Property<int>("warehouse_id")
                        .HasColumnType("int");

                    b.Property<string>("warehouse_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("goodslocation");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.GoodsOwnerEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contact_tel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("goods_owner_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_valid")
                        .HasColumnType("bit");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("manager")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("goodsowner");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.MenuEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("menu_actions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("menu_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("module")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sort")
                        .HasColumnType("int");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.Property<string>("vue_directory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vue_path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("vue_path_detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("menu");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.PrintSolutionEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("config_json")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("report_direction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("report_length")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("report_width")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("solution_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tab_page")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.Property<string>("vue_path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("user_defined_print_solution");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.RoleMenuEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<byte>("authority")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("menu_actions_authority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("menu_id")
                        .HasColumnType("int");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.Property<int>("userrole_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("rolemenu");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.SkuEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("bar_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("cost")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("height")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("lenght")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("price")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<string>("sku_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("sku_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("spu_id")
                        .HasColumnType("int");

                    b.Property<string>("unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("volume")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("weight")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<decimal>("width")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.HasKey("id");

                    b.HasIndex("spu_id");

                    b.ToTable("sku");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.SkuSafetyStockEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("safety_stock_qty")
                        .HasColumnType("int");

                    b.Property<int>("sku_id")
                        .HasColumnType("int");

                    b.Property<int>("warehouse_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("sku_id");

                    b.ToTable("sku_safety_stock");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.SpuEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("bar_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("category_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_valid")
                        .HasColumnType("bit");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime2");

                    b.Property<byte>("length_unit")
                        .HasColumnType("tinyint");

                    b.Property<string>("origin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("spu_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("spu_description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("spu_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("supplier_id")
                        .HasColumnType("int");

                    b.Property<string>("supplier_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.Property<byte>("volume_unit")
                        .HasColumnType("tinyint");

                    b.Property<byte>("weight_unit")
                        .HasColumnType("tinyint");

                    b.HasKey("id");

                    b.ToTable("spu");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.StockAdjustEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("expiry_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("goods_location_id")
                        .HasColumnType("int");

                    b.Property<int>("goods_owner_id")
                        .HasColumnType("int");

                    b.Property<bool>("is_update_stock")
                        .HasColumnType("bit");

                    b.Property<string>("job_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("job_type")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("price")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("putaway_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("qty")
                        .HasColumnType("int");

                    b.Property<string>("series_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sku_id")
                        .HasColumnType("int");

                    b.Property<int>("source_table_id")
                        .HasColumnType("int");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("stockadjust");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.StockEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("expiry_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("goods_location_id")
                        .HasColumnType("int");

                    b.Property<int>("goods_owner_id")
                        .HasColumnType("int");

                    b.Property<bool>("is_freeze")
                        .HasColumnType("bit");

                    b.Property<DateTime>("last_update_time")
                        .IsConcurrencyToken()
                        .HasColumnType("datetime2");

                    b.Property<decimal>("price")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("putaway_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("qty")
                        .HasColumnType("int");

                    b.Property<string>("series_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sku_id")
                        .HasColumnType("int");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("stock");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.StockFreezeEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("goods_location_id")
                        .HasColumnType("int");

                    b.Property<int>("goods_owner_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("handle_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("handler")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("job_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("job_type")
                        .HasColumnType("bit");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("series_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sku_id")
                        .HasColumnType("int");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("stockfreeze");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.StockMoveEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("dest_googs_location_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("expiry_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("goods_owner_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("handle_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("handler")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("job_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime2");

                    b.Property<byte>("move_status")
                        .HasColumnType("tinyint");

                    b.Property<int>("orig_goods_location_id")
                        .HasColumnType("int");

                    b.Property<decimal>("price")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("putaway_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("qty")
                        .HasColumnType("int");

                    b.Property<string>("series_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sku_id")
                        .HasColumnType("int");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("stockmove");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.StockProcessDetailEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("expiry_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("goods_location_id")
                        .HasColumnType("int");

                    b.Property<int>("goods_owner_id")
                        .HasColumnType("int");

                    b.Property<bool>("is_source")
                        .HasColumnType("bit");

                    b.Property<bool>("is_update_stock")
                        .HasColumnType("bit");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("price")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("putaway_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("qty")
                        .HasColumnType("int");

                    b.Property<string>("series_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sku_id")
                        .HasColumnType("int");

                    b.Property<int>("stock_process_id")
                        .HasColumnType("int");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("stock_process_id");

                    b.ToTable("stockprocessdetail");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.StockProcessEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("job_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("job_type")
                        .HasColumnType("bit");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime2");

                    b.Property<bool>("process_status")
                        .HasColumnType("bit");

                    b.Property<DateTime>("process_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("processor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("stockprocess");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.StockTakingEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("book_qty")
                        .HasColumnType("int");

                    b.Property<int>("counted_qty")
                        .HasColumnType("int");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("difference_qty")
                        .HasColumnType("int");

                    b.Property<DateTime>("expiry_date")
                        .HasColumnType("datetime2");

                    b.Property<int>("goods_location_id")
                        .HasColumnType("int");

                    b.Property<int>("goods_owner_id")
                        .HasColumnType("int");

                    b.Property<DateTime>("handle_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("handler")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("job_code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("job_status")
                        .HasColumnType("bit");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("price")
                        .HasPrecision(18, 6)
                        .HasColumnType("decimal(18,6)");

                    b.Property<DateTime>("putaway_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("series_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("sku_id")
                        .HasColumnType("int");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("stocktaking");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.SupplierEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contact_tel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_valid")
                        .HasColumnType("bit");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("manager")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("supplier_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("supplier");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.WarehouseAreaEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("area_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("area_property")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime2");

                    b.Property<bool>("is_valid")
                        .HasColumnType("bit");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime2");

                    b.Property<int>("parent_id")
                        .HasColumnType("int");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.Property<int>("warehouse_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("warehousearea");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.WarehouseEntity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("city")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contact_tel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("create_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("creator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("is_valid")
                        .HasColumnType("bit");

                    b.Property<DateTime>("last_update_time")
                        .HasColumnType("datetime2");

                    b.Property<string>("manager")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("tenant_id")
                        .HasColumnType("bigint");

                    b.Property<string>("warehouse_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("warehouse");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.AsnEntity", b =>
                {
                    b.HasOne("ModernWMS.WMS.Entities.Models.AsnMasterEntity", "Asnmaster")
                        .WithMany("detailList")
                        .HasForeignKey("asnmaster_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asnmaster");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.DispatchPickListEntity", b =>
                {
                    b.HasOne("ModernWMS.WMS.Entities.Models.DispatchListEntity", "Dispatchlist")
                        .WithMany("detailList")
                        .HasForeignKey("dispatchlist_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dispatchlist");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.FlowSetEntity", b =>
                {
                    b.HasOne("ModernWMS.WMS.Entities.Models.Approve.FlowSetMainEntity", "FlowMainSet")
                        .WithMany("flowset_list")
                        .HasForeignKey("flowsetmain_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlowMainSet");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.FlowSetFilterEntity", b =>
                {
                    b.HasOne("ModernWMS.WMS.Entities.Models.FlowSetEntity", "FlowSet")
                        .WithMany("filter_list")
                        .HasForeignKey("flowset_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlowSet");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.FlowSetUserEntity", b =>
                {
                    b.HasOne("ModernWMS.WMS.Entities.Models.FlowSetEntity", "FlowSet")
                        .WithMany("user_list")
                        .HasForeignKey("flowset_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FlowSet");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.SkuEntity", b =>
                {
                    b.HasOne("ModernWMS.WMS.Entities.Models.SpuEntity", "Spu")
                        .WithMany("detailList")
                        .HasForeignKey("spu_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Spu");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.SkuSafetyStockEntity", b =>
                {
                    b.HasOne("ModernWMS.WMS.Entities.Models.SkuEntity", "Sku")
                        .WithMany("detailList")
                        .HasForeignKey("sku_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sku");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.StockProcessDetailEntity", b =>
                {
                    b.HasOne("ModernWMS.WMS.Entities.Models.StockProcessEntity", "StockProcess")
                        .WithMany("detailList")
                        .HasForeignKey("stock_process_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("StockProcess");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.Approve.FlowSetMainEntity", b =>
                {
                    b.Navigation("flowset_list");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.AsnMasterEntity", b =>
                {
                    b.Navigation("detailList");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.DispatchListEntity", b =>
                {
                    b.Navigation("detailList");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.FlowSetEntity", b =>
                {
                    b.Navigation("filter_list");

                    b.Navigation("user_list");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.SkuEntity", b =>
                {
                    b.Navigation("detailList");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.SpuEntity", b =>
                {
                    b.Navigation("detailList");
                });

            modelBuilder.Entity("ModernWMS.WMS.Entities.Models.StockProcessEntity", b =>
                {
                    b.Navigation("detailList");
                });
#pragma warning restore 612, 618
        }
    }
}
